name: Mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.15 # Pastikan indentasi di sini benar

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Menambahkan aset
  assets:
    - assets/logo.jpg
    - assets/wahida.jpg
    - assets/prasasta.jpg
    - assets/defi.jpg
    - assets/ardhana.jpg
    - assets/ardha.jpg
    - assets/bl.jpg
    - data/users.json
    - data/messages.json
    - data/notifications.json
